### PR TITLE
Core modules and plugins

### PR DESCRIPTION
**Pull request by gmarcos87**
Create packages for core modules and plugins. Remove from the main repository and add as dependencies. And improved navigation between nodes

### CODE REVIEW

**Comment by gmarcos87** [comment]
@nicoechaniz or @nicopace

**Comment by nicopace** [comment]
The production server doesn't work.

This is the error:
```
> preact-limeapp@0.0.2 start /tmp/lime-app
> serve build -s -c 1

/tmp/lime-app/node_modules/serve/bin/serve.js:11
const {coroutine} = require('bluebird')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

npm ERR! Linux 4.8.0-54-generic
npm ERR! argv "/home/nicopace/.virtualenvs/nodejs/bin/node" "/home/nicopace/.virtualenvs/nodejs/bin/npm" "start"
npm ERR! node v5.12.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! preact-limeapp@0.0.2 start: `serve build -s -c 1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the preact-limeapp@0.0.2 start script 'serve build -s -c 1'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the preact-limeapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     serve build -s -c 1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs preact-limeapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls preact-limeapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/lime-app/npm-debug.log
```

The development server, and the manual build works perfectly.

The output production build weights ~600kb... is that ok? I thought we were ~40kb.

**Comment by gmarcos87** [comment]
Are you in a new clone? The dependencies in package.json changed a lot, rerun ```npm install``` and try again.
The 40kb weight its for core functions, the current package includes a lot of extras dependencies, plugins and source maps. In a future version we will reduce some of that.

**Comment by nicopace** [comment]
@gmarcos87 I did a clean clone in /tmp.

**Comment by gmarcos87** [comment]
I have read your error log more carefully. You are using an older version of NodeJs (5.x), that is the problem. Upgrade to a [newer, more stable version](https://github.com/nodejs/LTS#lts-schedule1) (6.x or higher).

**Comment by nicopace** [comment]
Great. will do, will try, will report :)

**Comment by nicopace** [comment]
Tested, it works. Merging!

**Pull request merged**
