### PR TITLE
New align screen

### LINKED ISSUE #169: Refresh allignable clients dynamically
in the align screen, in adhoc mode, if your neighbour is not there when you load the screen, no matter if you align the antenna or not you don't see your neighbour again.

### PR DESCRIPTION
**Pull request by germanferrero**
**This PR introduces major changes in the Align Screen.**

Before the screen looked like this:

And now like this (plus the header):

This screen let's you see all the stations associated at each radio at once.
Also you can click at one of them and have a single radio-node screen like the one we had before.

**Some bugs are fixed:**
- Refresh the associated nodes more quickly: Before the _assoclist_ was fetched only when entering the Align screen. Only the signal of the current selected node was refreshed periodically. Now the entire _assoclist_ is refreshed every 2 seconds. Including new signal values. Fixes: https://github.com/libremesh/lime-app/issues/169
- Better handling of no associated nodes in one radio: Before when selecting a radio without associated nodes, the LimeApp would automatically switch to the other radio. It now shows a clear message that the radio has no nodes associated to it.

- Tell the user that the neighbor is not associated anymore: Before, when the neighbor became not associated the LimeApp would keep displaying the last signal value. The screen now shows you a clear message of this situation including when the last packet was sent (inactive time).

(Also shown in list mode)

**And some new features / enhancements:**
- Retrieve the hostname of each neighbor with a fe80 request if not present in shared state.
- Show the best achieved signal during the screen session. Useful during alignment process.

**For developers**
- Add tests
- Migrate align screen from rxjs + redux to useState + react-query

This PR has a companion branch at lime-packages: https://github.com/germanferrero/lime-packages/tree/new-align-screen which introduces breaking changes for previous lime-app versions. So we could test this PR against it, do a limeapp release, and then create a PR at lime-packages including the new lime-app and the necessary back-end changes all together.

You can check the storybook for this PR here:
https://germanferrero.github.io/lime-app

### CODE REVIEW

**Comment by spiccinini** [comment]
Wow! Impresive work!!! This will be very useful. I will be testing and report back.

A little thing, that maybe is my engineering background as a profesional deformation, is that the numbers should be acompanied somehow of its units (dBm in this case). Do you think that it is possible to add the units? I think that the purpose of adding the units is more educational than only nitpick as then dBm and dB will then be useful for link budget calculations. Anytway this is not a request, just my opinion.

**Comment by gmarcos87** [comment]
🤩🤩🤩🤩

**Comment by germanferrero** [comment]
> A little thing, that maybe is my engineering background as a profesional deformation, is that the numbers should be acompanied somehow of its units (dBm in this case). Do you think that it is possible to add the units? I think that the purpose of adding the units is more educational than only nitpick as then dBm and dB will then be useful for link budget calculations. Anytway this is not a request, just my opinion.

I like the idea :) We can add the units with no big effort.
Also, I'm thinking that 'from its radio 1' would be better than the actual 'at its radio 1'. Since the signal number represents the strength of the signal coming from the neighbor radio.

**Comment by nicopace** [comment]
Impressive Work!

A couple of suggestions:
* the list of associated nodes could have a header describing that those are associated nodes (so users don't need to guess it the first time)
* The story `/story/containers-align-screen--align-row-not-associated`, instead of saying "No enlazado" it could be a little bit more descriptive so it doesn't require someone to explain what it is. Maybe something more like "Lost signal" might work better, as users are used to that slang.
* Maybe somewhere we could display the color coding, like "what do you mean with green or red", I think it goes in the line of the engineering background of the units, this is also a unit that is not being specified.
* Together with the color coding, I think there is a predefined range of "very good", "good enough" and "crappy" link quality... maybe there is a conversation to have there? I am sure the recommendation is "the higher the better" when aligning, but it is also all too frequent to hear "how good is good enough?" that could rephrased as "when is it bad enough to work harder on a link?".
* the raw view in `https://germanferrero.github.io/lime-app/?path=/story/containers-align-screen--fetching-neighbor-name` has a redundant "En su radio 1", because it is already in the "radio 1" section.

**Comment by germanferrero** [comment]
> Impressive Work!
> 
> A couple of suggestions:
> 
>     * the list of associated nodes could have a header describing that those are associated nodes (so users don't need to guess it the first time)
I Agree, we can add it :)

> 
>     * The story `/story/containers-align-screen--align-row-not-associated`, instead of saying "No enlazado" it could be a little bit more descriptive so it doesn't require someone to explain what it is. Maybe something more like "Lost signal" might work better, as users are used to that slang.
> 
Yes!! much better!

>     * Maybe somewhere we could display the color coding, like "what do you mean with green or red", I think it goes in the line of the engineering background of the units, this is also a unit that is not being specified.
> 
>     * Together with the color coding, I think there is a predefined range of "very good", "good enough" and "crappy" link quality... maybe there is a conversation to have there? I am sure the recommendation is "the higher the better" when aligning, but it is also all too frequent to hear "how good is good enough?" that could rephrased as "when is it bad enough to work harder on a link?".
Hmm, I agree that it's better to be explicit here rather than implicit. Today many communities learn by themselves how   good is good enough or how bad is bad enough. I would like to address this issue in a future PR.

>     * the raw view in `https://germanferrero.github.io/lime-app/?path=/story/containers-align-screen--fetching-neighbor-name` has a redundant "En su radio 1", because it is already in the "radio 1" section.
Hm not actually, the idea of "En su radio 1" which has been rephrased to "Desde su radio 1 / From its radio 1" is to inform which radio of your neighbor node is associated with your own radio. It may be the case that you are aligning radio1 against radio 2 in devices with multiple 5ghz radios. I think this information could be useful... what do you think?

**Comment by nicopace** [comment]
> Hm not actually, the idea of "En su radio 1" which has been rephrased to "Desde su radio 1 / From its radio 1" is to inform which radio of your neighbor node is associated with your own radio. It may be the case that you are aligning radio1 against radio 2 in devices with multiple 5ghz radios. I think this information could be useful... what do you think?

Now I get it, but it was not intuitive to read it... there seems to be an assumption there, but I cannot detect which one... will think about it a little bit.

**Comment by spiccinini** [comment]
I've tested the new screen. It is awesome and works very well!!!


I would change the "From its radioN" to "To its radioN".

I think that the next breakthrough would be to show the pair "rx-me/rx-peer" (now we are showing rx-me only).  Obviously not for this PR!

image

**Pull request merged**
