### PR TITLE
Add messages and screenshots for translatable strings

### PR DESCRIPTION
**Pull request by patogit**
Here is the updated qqq.json file with message documentation to help translators understand what they're translating.

Some issues:

No translation file entry for "Edit location" button in this screenshot https://raw.githubusercontent.com/patogit/lime-app/screenshots/05-station-edit-location-map.png

Need context for https://raw.githubusercontent.com/patogit/lime-app/screenshots/04-interfaces-stations.png . What do I tap on in order to get to this screen / What is this screen called / What do I do on this screen?

No translation file entry for "Set new location" button in this screenshot
https://raw.githubusercontent.com/patogit/lime-app/screenshots/06-set-as-new-location.png

Do we call them stations or nodes? Both terms are used in different places. This is the first time I've heard them called stations.

What's the difference between base host and connected host? What's the name of this screen? https://raw.githubusercontent.com/patogit/lime-app/screenshots/09-current-status-select-new-change.png

What's the function of the Only Gateway button on this screen:
https://raw.githubusercontent.com/patogit/lime-app/screenshots/12-bottom-node-list.png

No screenshot for the following messages:
"back_to_base_443797cb" :"Back to base",
"load_last_known_internet_path_677f6229" :"Load last known Internet path",
"metrics_status_stations_464641e8" :"Measuring links",
"move_to_new_position_eb97c4c3" :"MOVE TO NEW POSITION",
"packet_loss_1afe48a8": "Packet loss",

### CODE REVIEW

**Comment by gmarcos87** [comment]
Hello Pato, in order to answer your queries it is necessary that you first update the status of your pull request. Please update your fork and then in the branch translate make a _git rebase develop_. Then when you do a _git push --force translate_ the changes will be displayed correctly.
Greetings

**Comment by patogit** [comment]
I figured out how to rebase in the GitHub GUI interface and did it yesterday

**Comment by gmarcos87** [comment]
Yeah, but develop was behind master's, which shouldn't happen again. There I updated develop, but you need to update the pull request again.

**Comment by patogit** [comment]
I am trying to do what you suggest, and it isn't working. This is the first time I'm using git command line. I set my username and email to match GitHub, but git hasn't asked me for a password.

[user@system lime-app]$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
[user@system lime-app]$ git merge upstream/master
Already up to date.
[user@system lime-app]$ git checkout screenshots
Switched to branch 'screenshots'
Your branch is up to date with 'origin/screenshots'.
[user@system lime-app]$ git merge upstream/master
fatal: refusing to merge unrelated histories
[user@system lime-app]$ git merge upstream/screenshots
Already up to date.
[user@system lime-app]$ git rebase develop
fatal: Needed a single revision
invalid upstream develop
[user@system lime-app]$ git checkout translate
Branch 'translate' set up to track remote branch 'translate' from 'origin'.
Switched to a new branch 'translate'
[user@system lime-app]$ git rebase develop
fatal: Needed a single revision
invalid upstream develop
[user@system lime-app]$ git push --force translate
fatal: 'translate' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by patogit** [comment]
Tried this with no success... maybe I should be logged in to GitHub somehow from the command line?

[user@system lime-app]$ git rebase --interactive
Successfully rebased and updated refs/heads/translate.
[user@system lime-app]$ git rebase -i ab8d29e23fd6557e8588d2a6b504b813b9fe7f4e
Successfully rebased and updated refs/heads/translate.

Both of those open up a text editor window with the following text:

> noop
> 
> # Rebase ab8d29e..ab8d29e onto ab8d29e (1 command)
> #
> # Commands:
> # p, pick = use commit
> # r, reword = use commit, but edit the commit message
> # e, edit = use commit, but stop for amending
> # s, squash = use commit, but meld into previous commit
> # f, fixup = like "squash", but discard this commit's log message
> # x, exec = run command (the rest of the line) using shell
> # d, drop = remove commit
> #
> # These lines can be re-ordered; they are executed from top to bottom.
> #
> # If you remove a line here THAT COMMIT WILL BE LOST.
> #
> # However, if you remove everything, the rebase will be aborted.
> #
> # Note that empty commits are commented out
>

**Comment by patogit** [comment]
@aparcar is helping me with this, and since my commits are pretty simple, and in a file that probably wasn't changed by anything @gmarcos87 did, maybe it's easier to trash this commit and copy my changes to a new branch that's done properly, and make a new pull request....?

**Comment by patogit** [comment]
got the git issues sorted out with help from @gmarcos87 and @aparcar

**Comment by gmarcos87** [comment]
Great work!

**Pull request merged**
