### PR TITLE
Fw upgrade one click

### PR DESCRIPTION
**Pull request by germanferrero**
This PR adds support for one-click installation in companion with https://github.com/libremesh/lime-packages/pull/773

- A banner is shown above the header saying that there is a new firmware version available when there is one.
- New release section is added to firmware upgrade screen. In there, the user can trigger release downloading, and upgrading from it.

Also [React Query](https://react-query.tanstack.com/) is introduced to the code base. React query allows to separate server state handling logic from UI state. The best feature IMO being letting developers re-use server state data across components in a declarative way, without worrying about caching and de-duping.

### CODE REVIEW

**Comment by germanferrero** [comment]
CI is failing at storybook build, because of a simple typo in the storybook repo, which will be solved when https://github.com/storybookjs/storybook/pull/12883 gets merged.

**Comment by ilario** [comment]
Wow this is huge! Thanks @germanferrero!
Does this PR depend from libremesh/lime-packages#773 or can we merge this before merging  libremesh/lime-packages#773?
Needless to say, as https://github.com/libremesh/lime-packages/issues/763 and https://github.com/libremesh/lime-app/issues/275 are release blockers and this PR includes a patch, I would push towards merging this as soon as possible. @germanferrero @spiccinini do you think we can merge this already?

**Comment by germanferrero** [comment]
@ilario I've opened #279 with the patch, so we do not depend on merging all this before. Sorry for the anti-pattern of coupling an urgent path with a new big feature.

**Review by spiccinini — APPROVED** [review]
I've tested it and skimed through the code. It looks much more clear. Great work!

**Comment by germanferrero** [comment]
I close this, since all changes were added by merging #278. Thanks

**Pull request closed without merging**
