### PR TITLE
Updates deps and lint

### PR DESCRIPTION
**Pull request by fnbellomo**
## Features

- Docker to make local development easier
- Add `package-lock.json` and remove from  `.gitignore`
- Update all the deps and add some missing like `dotenv`
  - `react-query@2` now is `@tanstack/react-query@4` and have some breaking change:
    - [From version 2 (current) to 3](https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-3)
    - [From 3 to 4](https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4)
  - [Migrate](https://github.com/storybookjs/storybook/blob/next/code/addons/controls/README.md#how-do-i-migrate-from-addon-knobs) `@storybook/addon-knobs` to `@storybook/addon-controls`
  - We went from 75 vulnerabilities to 35 (18 from `preact-cli` and the rest from `storybook`)
- I added [prettier](https://prettier.io/), configured it with `eslint` and ran the linters against all files.
- Add the linter to the [husky](https://github.com/typicode/husky)

## Breaking changes

- Update `react-query` import

```diff
- import { useMutation, useQuery } from "react-query";
+ import { useMutation, useQuery } from "@tanstack/react-query";
```

- The query/mutations are not more iterables

```diff
import { useLogin } from "utils/queries";

- const [login, { isError }] = useLogin();
+ const { mutate: login, isError } = useLogin();
```

- It is no longer necessary to `import { h } from preact`, it is already imported in babel.

- Storybook: [Replace](https://github.com/storybookjs/storybook/blob/master/lib/core/docs/storiesOf.md) old `storiesOf` api with `CSR`

Disclaimer: The PR has many files automatically modified by the linter

### CODE REVIEW

**Comment by G10h4ck** [comment]
I see it's about 70K line changes, is something generated automatically ending up in the repository? In that case we should see how to avoid this

**Comment by nicopace** [comment]
Awesome!!!
I would split the prettier changes in a separate PR, so the change becomes more clear.

**Comment by fnbellomo** [comment]
> In that case we should see how to avoid this

Now the linter is configured with git to run on every commit, so this is going to happen automatically on every commit

**Comment by selankon** [comment]
@fnbellomo I guess this should be closed in substitution of #346 to split the changes on little PRs.

**Comment by selankon** [comment]
Closed in favour of #346

**Pull request closed without merging**
